[package]
name = "symbol-tx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ed25519-dalek = "1"
hex = "0.4.3"
rand = "0.7.3"
base32 = "0.4.0"
ureq = "*"
sha3 = "0.10.1"
chrono = "*"